export const MOCK_NOTICES = [
    {
        id: '1',
        eventId: '2',
        title: 'Mudança de Horário - Finais',
        category: 'Urgente',
        description: 'Atenção a todos os participantes: As finais do futsal foram adiantadas para as 14h devido à previsão de chuva.',
        date: new Date('2024-03-15'),
        time: '10:00',
        author: 'Organização',
        createdAt: new Date('2024-03-15T10:00:00'),
    },
    {
        id: '2',
        eventId: '2',
        title: 'Estacionamento Liberado',
        category: 'Informativo',
        description: 'O estacionamento do complexo esportivo estará liberado gratuitamente para todos os atletas e comissão técnica.',
        date: new Date('2024-03-14'),
        time: '09:30',
        author: 'Staff',
        createdAt: new Date('2024-03-14T09:30:00'),
    },
    {
        id: '3',
        eventId: '2',
        title: 'Entrega de Kits',
        category: 'Plantão',
        description: 'A entrega dos kits será realizada no ginásio principal até às 18h de hoje.',
        date: new Date('2024-03-13'),
        time: '08:00',
        author: 'Coordenação',
        createdAt: new Date('2024-03-13T08:00:00'),
    },
    {
        id: '4',
        eventId: '2',
        title: 'Reunião Técnica',
        category: 'Últimas Notícias',
        description: 'Reunião técnica obrigatória para todos os representantes de equipe hoje às 19h.',
        date: new Date('2024-03-12'),
        time: '18:00',
        author: 'Direção Técnica',
        createdAt: new Date('2024-03-12T18:00:00'),
    },
    {
        id: '5',
        eventId: '2',
        title: 'Achados e Perdidos',
        category: 'Informativo',
        description: 'Um par de tênis Nike foi encontrado na quadra 2. Retirar na secretaria do evento.',
        date: new Date('2024-03-16'),
        time: '11:00',
        author: 'Secretaria',
        createdAt: new Date('2024-03-16T11:00:00'),
    },
    {
        id: '6',
        eventId: '2',
        title: 'Festa de Encerramento',
        category: 'Últimas Notícias',
        description: 'A festa de encerramento contará com música ao vivo e premiações especiais. Não percam!',
        date: new Date('2024-03-20'),
        time: '20:00',
        author: 'Marketing',
        createdAt: new Date('2024-03-20T20:00:00'),
    }
]
