export const MOCK_BULLETINS = [
    {
        id: '1',
        eventId: '2',
        title: 'Boletim 01 - Programação Geral',
        category: 'Programação',
        description: 'Confira a programação completa dos jogos da primeira fase.',
        date: new Date('2024-03-10'),
        time: '08:00',
        author: 'Direção Técnica',
        fileName: 'boletim_01.pdf',
        createdAt: new Date('2024-03-10T08:00:00'),
    },
    {
        id: '2',
        eventId: '2',
        title: 'Boletim 02 - Resultados Dia 1',
        category: 'Resultados Oficiais',
        description: 'Resultados de todas as partidas realizadas no primeiro dia de competição.',
        date: new Date('2024-03-11'),
        time: '22:00',
        author: 'Arbitragem',
        fileName: 'resultados_dia_1.pdf',
        createdAt: new Date('2024-03-11T22:00:00'),
    },
    {
        id: '3',
        eventId: '2',
        title: 'Boletim 03 - Alteração de Tabela',
        category: 'Nota Oficial',
        description: 'Nota oficial sobre a alteração na tabela de jogos do vôlei feminino.',
        date: new Date('2024-03-12'),
        time: '14:00',
        author: 'Coordenação',
        fileName: 'nota_oficial_01.pdf',
        createdAt: new Date('2024-03-12T14:00:00'),
    },
    {
        id: '4',
        eventId: '2',
        title: 'Boletim 04 - Classificação Parcial',
        category: 'Resultados Oficiais',
        description: 'Classificação atualizada de todos os grupos após a segunda rodada.',
        date: new Date('2024-03-13'),
        time: '10:00',
        author: 'Técnica',
        fileName: 'classificacao_parcial.pdf',
        createdAt: new Date('2024-03-13T10:00:00'),
    },
    {
        id: '5',
        eventId: '2',
        title: 'Boletim 05 - Programação Finais',
        category: 'Programação',
        description: 'Horários e locais definidos para as grandes finais.',
        date: new Date('2024-03-14'),
        time: '16:00',
        author: 'Organização',
        fileName: 'finais.pdf',
        createdAt: new Date('2024-03-14T16:00:00'),
    },
    {
        id: '6',
        eventId: '2',
        title: 'Boletim 06 - Encerramento',
        category: 'Boletim Diário',
        description: 'Informações sobre a cerimônia de encerramento e premiação.',
        date: new Date('2024-03-15'),
        time: '09:00',
        author: 'Cerimonial',
        fileName: 'cerimonia.pdf',
        createdAt: new Date('2024-03-15T09:00:00'),
    }
]
