export const INITIAL_MODALITIES = [
    {
        id: '1',
        name: 'Futsal',
        type: 'coletiva',
        gender: 'masculino',
        minAthletes: 5,
        maxAthletes: 12,
        maxEventsPerAthlete: 1,
        maxTeams: 16,
        minAge: 14,
        maxAge: 17,
    },
    {
        id: '2',
        name: 'Natação 50m Livre',
        type: 'individual',
        gender: 'feminino',
        eventCategory: '50m Livre',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 3,
        maxTeams: 0,
        minAge: 10,
        maxAge: 99,
    },
    {
        id: '3',
        name: 'Vôlei',
        type: 'coletiva',
        gender: 'feminino',
        minAthletes: 6,
        maxAthletes: 14,
        maxEventsPerAthlete: 1,
        maxTeams: 8,
        minAge: 16,
        maxAge: 99,
    },
    {
        id: '4',
        name: 'Atletismo 100m',
        type: 'individual',
        gender: 'masculino',
        eventCategory: '100m Rasos',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 3,
        maxTeams: 0,
        minAge: 12,
        maxAge: 99,
    },
    {
        id: '5',
        name: 'Handebol',
        type: 'coletiva',
        gender: 'masculino',
        minAthletes: 7,
        maxAthletes: 14,
        maxEventsPerAthlete: 1,
        maxTeams: 12,
        minAge: 14,
        maxAge: 17,
    },
    {
        id: '6',
        name: 'Basquete',
        type: 'coletiva',
        gender: 'feminino',
        minAthletes: 5,
        maxAthletes: 12,
        maxEventsPerAthlete: 1,
        maxTeams: 12,
        minAge: 14,
        maxAge: 17,
    },
    {
        id: '7',
        name: 'Judô - Leve',
        type: 'individual',
        gender: 'misto',
        eventCategory: '-60kg',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 1,
        maxTeams: 0,
        minAge: 10,
        maxAge: 18,
    },
    {
        id: '8',
        name: 'Ginástica Rítmica',
        type: 'individual',
        gender: 'feminino',
        eventCategory: 'Individual Geral',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 1,
        maxTeams: 0,
        minAge: 8,
        maxAge: 15,
    },
    {
        id: '9',
        name: 'Tênis de Mesa',
        type: 'individual',
        gender: 'misto',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 2,
        maxTeams: 0,
        minAge: 10,
        maxAge: 99,
    },
    {
        id: '10',
        name: 'Xadrez',
        type: 'individual',
        gender: 'misto',
        minAthletes: 1,
        maxAthletes: 1,
        maxEventsPerAthlete: 1,
        maxTeams: 0,
        minAge: 6,
        maxAge: 99,
    },
]

export const MOCK_PREVIEW_MODALITIES = {
    'mock1': { name: 'Futsal Sub-15', gender: 'masculino', minAge: 13, maxAge: 15, type: 'coletiva' },
    'mock2': { name: 'Vôlei de Praia', gender: 'feminino', minAge: 14, maxAge: 16, type: 'coletiva' },
    'mock3': { name: 'Xadrez', gender: 'misto', minAge: 8, maxAge: 18, type: 'individual' },
    'mock4': { name: 'Atletismo 100m', gender: 'masculino', minAge: 15, maxAge: 17, type: 'individual' },
    'mock5': { name: 'Handebol', gender: 'feminino', minAge: 12, maxAge: 14, type: 'coletiva' },
}

export const MOCK_LINKED_MODALITIES = [
    {
        id: 1,
        type: 'Coletiva',
        modality: 'Futebol',
        prova: '-',
        sex: 'Feminino',
        ageRange: '12 a 14',
    },
    {
        id: 2,
        type: 'Individual',
        modality: 'Natação',
        prova: 'Nado Costas',
        sex: 'Feminino',
        ageRange: '12 a 14',
    },
    {
        id: 3,
        type: 'Individual',
        modality: 'Natação',
        prova: 'Nado Livre',
        sex: 'Feminino',
        ageRange: '12 a 14',
    },
]
