export const MOCK_REGULATIONS = [
    {
        id: '1',
        eventId: '2',
        title: 'Regulamento Geral Jogos 2024',
        category: 'Geral',
        description: 'Documento completo com todas as normas e diretrizes dos jogos deste ano.',
        date: new Date('2024-01-15'),
        time: '08:00',
        author: 'Presidência',
        fileName: 'regulamento_geral_2024.pdf',
        createdAt: new Date('2024-01-15T08:00:00'),
    },
    {
        id: '2',
        eventId: '2',
        title: 'Regulamento Específico - Futsal',
        category: 'Específico',
        description: 'Regras específicas para a modalidade de Futsal.',
        date: new Date('2024-01-20'),
        time: '09:00',
        author: 'Coord. Futsal',
        fileName: 'reg_futsal.pdf',
        createdAt: new Date('2024-01-20T09:00:00'),
    },
    {
        id: '3',
        eventId: '2',
        title: 'Código de Justiça Desportiva',
        category: 'Código de Justiça',
        description: 'Código disciplinar aplicável a todas as infrações durante o evento.',
        date: new Date('2024-01-10'),
        time: '10:00',
        author: 'Jurídico',
        fileName: 'cjd_2024.pdf',
        createdAt: new Date('2024-01-10T10:00:00'),
    },
    {
        id: '4',
        eventId: '2',
        title: 'Norma Complementar 01 - Uniformes',
        category: 'Norma Complementar',
        description: 'Esclarecimentos sobre a padronização e uso de uniformes.',
        date: new Date('2024-02-01'),
        time: '14:00',
        author: 'Técnica',
        fileName: 'nc_01_uniformes.pdf',
        createdAt: new Date('2024-02-01T14:00:00'),
    },
    {
        id: '5',
        eventId: '2',
        title: 'Regulamento Específico - Vôlei',
        category: 'Específico',
        description: 'Regras específicas para a modalidade de Voleibol.',
        date: new Date('2024-01-22'),
        time: '09:00',
        author: 'Coord. Vôlei',
        fileName: 'reg_volei.pdf',
        createdAt: new Date('2024-01-22T09:00:00'),
    },
    {
        id: '6',
        eventId: '2',
        title: 'Edital de Convocação',
        category: 'Edital',
        description: 'Convocação para o congresso técnico inicial.',
        date: new Date('2024-02-15'),
        time: '18:00',
        author: 'Diretoria',
        fileName: 'edital_convocacao.pdf',
        createdAt: new Date('2024-02-15T18:00:00'),
    }
]
